In [1]:
import numpy as np

In [9]:
import numpy as np

#(a)Construct a matrix as a NumPy array
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 0]])

#(a) Computing the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)


Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 0. ]]

Inverse Matrix:
[[ 0.87671233 -0.54794521  0.46575342]
 [-0.54794521  0.34246575  0.95890411]
 [ 0.46575342  0.95890411 -1.31506849]]


In [10]:
# computing the derterminat 
import numpy as np


matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 0]])


#(b) Computing the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

#(c) Decomposing the matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Determinant: -0.7300000000000001
Eigenvalues: [ 1.70914434  0.81495271 -0.52409705]
Eigenvectors:
[[-0.53521254 -0.81268265 -0.23042232]
 [-0.69408264  0.57856585 -0.42838166]
 [-0.48145283  0.06934311  0.87372462]]
